[package]
name = "renamer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
regex = "1.11.1"
walkdir = "2.5.0"
log = "0.4.14"
simplelog = "0.11.0"
anyhow = "1.0"
rayon = "1.7"

[dev-dependencies]
tempfile = "3.3"
